# Generated by Django 2.2.3 on 2019-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='console',
            new_name='character',
        ),
        migrations.AddField(
            model_name='game',
            name='consoles',
            field=models.ManyToManyField(to='main_app.Console'),
        ),
    ]
